title: Hikari's Security Blog
author: Hikari
description: > # this means to ignore newlines until "show_exerpts:"
  Welcome to Hikari's Security Blog. You are invited to browse an extensive collection of my learning projects, experiments, wins and failures.
  You can expect to find writeups for CTF challenges and HackTheBox machines, as well as other security-related exercises, best practices and learning resources.
  Feel free to browse around.
  Keep hacking (^-^)
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: hikarihacks-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://github.com/hikarihacks
      icon: github-square
      color: purple

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  #avatar_source: github
  #github_username: bitbrain
  avatar_source: local
  avatar_path: /assets/avatar.jpg

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
